"""
Weekly email report generator + sender.

Renders a plain-text and HTML summary of the past week's classifications,
highlighting:
  - Total calls processed
  - Distribution of Call Reasons / Job Types
  - Missed booking opportunities (these should have been jobs but weren't)
  - Low-confidence classifications that need human review
  - Individual call details for missed bookings (so Taylor can action them)

Email is sent via the Resend HTTP API (preferred) or SMTP fallback.
For Railway deploy, set RESEND_API_KEY in environment variables.
"""

from __future__ import annotations

import json
import os
import smtplib
import sys
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Iterable, Optional
from urllib.request import Request, urlopen
from urllib.error import HTTPError

from .models import Classification


def render_text_report(
    *,
    start_date: date,
    end_date: date,
    classifications: Iterable[Classification],
    total_st_calls: int = 0,
    matched_dialpad: int = 0,
    written_back: int = 0,
    reason_field_updated: int = 0,
) -> str:
    """Plain-text version of the weekly report."""
    classifications = list(classifications)
    total = len(classifications)

    by_type: dict[str, int] = {"call_reason": 0, "job_type": 0}
    by_value: dict[str, int] = {}
    missed: list[Classification] = []
    low_conf: list[Classification] = []
    for c in classifications:
        by_type[c.classification_type] = by_type.get(c.classification_type, 0) + 1
        by_value[c.classification_value] = by_value.get(c.classification_value, 0) + 1
        if c.should_have_been_booked:
            missed.append(c)
        if c.confidence < 0.6:
            low_conf.append(c)

    lines = [
        "=" * 60,
        "C&R SERVICES — CALL CLASSIFICATION REPORT",
        "=" * 60,
        f"Period: {start_date} to {end_date}",
        f"Total calls in ServiceTitan: {total_st_calls}",
        f"Matched to Dialpad: {matched_dialpad}",
        f"Classified by AI: {total}",
        f"  - Assigned a Call Reason: {by_type.get('call_reason', 0)}",
        f"  - Assigned a Job Type: {by_type.get('job_type', 0)}",
    ]

    if written_back > 0:
        lines.extend([
            "",
            f"ServiceTitan Updates: {written_back} calls written back",
            f"  - Call Reason field updated: {reason_field_updated}",
            f"  - Memo-only (no ST reason match): {written_back - reason_field_updated}",
        ])

    lines.extend([
        "",
        "-" * 60,
        "CLASSIFICATION DISTRIBUTION",
        "-" * 60,
    ])
    for value, count in sorted(by_value.items(), key=lambda kv: -kv[1]):
        pct = (count / total * 100) if total else 0
        lines.append(f"  {count:>4}  ({pct:4.1f}%)  {value}")

    lines.extend([
        "",
        "-" * 60,
        f"MISSED BOOKING OPPORTUNITIES: {len(missed)}",
        "-" * 60,
    ])
    if missed:
        lines.append("These calls look like a job should have been booked but wasn't:")
        lines.append("")
        for c in missed[:30]:  # Cap at 30 to keep email readable
            lines.append(f"  Call {c.call_id}:")
            lines.append(f"    Recommended Job Type: {c.booking_recommendation or c.classification_value}")
            lines.append(f"    Confidence: {c.confidence:.0%}")
            lines.append(f"    Reason: {c.reasoning}")
            lines.append("")
        if len(missed) > 30:
            lines.append(f"  ... and {len(missed) - 30} more.")
    else:
        lines.append("  None! All bookable calls appear to be properly booked.")

    lines.extend([
        "",
        "-" * 60,
        f"LOW-CONFIDENCE CLASSIFICATIONS: {len(low_conf)}",
        "-" * 60,
    ])
    if low_conf:
        lines.append("These need human review (classifier wasn't confident):")
        lines.append("")
        for c in low_conf[:20]:
            lines.append(f"  Call {c.call_id}: {c.classification_value} ({c.confidence:.0%})")
        if len(low_conf) > 20:
            lines.append(f"  ... and {len(low_conf) - 20} more.")
    else:
        lines.append("  None! All classifications are above the confidence threshold.")

    lines.extend([
        "",
        "=" * 60,
        f"Generated by C&R Call Classifier ({classifications[0].classifier_version if classifications else 'n/a'})",
        "=" * 60,
    ])
    return "\n".join(lines)


def render_html_report(
    *,
    start_date: date,
    end_date: date,
    classifications: Iterable[Classification],
    total_st_calls: int = 0,
    matched_dialpad: int = 0,
    written_back: int = 0,
    reason_field_updated: int = 0,
) -> str:
    """HTML version for prettier email rendering."""
    text = render_text_report(
        start_date=start_date,
        end_date=end_date,
        classifications=classifications,
        total_st_calls=total_st_calls,
        matched_dialpad=matched_dialpad,
        written_back=written_back,
        reason_field_updated=reason_field_updated,
    )
    # Simple HTML wrapper — keeps it readable in all email clients.
    escaped = (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
<h2 style="color: #1a1a1a;">C&amp;R Services — Call Classification Report</h2>
<p style="color: #666;">Period: {start_date} to {end_date}</p>
<pre style="font-family: 'SF Mono', 'Fira Code', Consolas, monospace; font-size: 13px; line-height: 1.5; background: #f8f9fa; padding: 16px; border-radius: 8px; overflow-x: auto; white-space: pre-wrap;">{escaped}</pre>
</body>
</html>"""


def send_report(
    *,
    subject: str,
    text_body: str,
    html_body: str,
    recipients: list[str],
    from_address: Optional[str] = None,
) -> None:
    """Send the report via Resend HTTP API (preferred) or SMTP fallback.

    Resend (preferred): set RESEND_API_KEY and optionally RESEND_FROM.
    SMTP fallback: set SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, SMTP_FROM.
    """
    resend_key = os.environ.get("RESEND_API_KEY", "")
    if resend_key:
        _send_via_resend(
            api_key=resend_key,
            subject=subject,
            text_body=text_body,
            html_body=html_body,
            recipients=recipients,
            from_address=from_address or os.environ.get("RESEND_FROM", "C&R Call Classifier <onboarding@resend.dev>"),
        )
        return

    # SMTP fallback
    _send_via_smtp(
        subject=subject,
        text_body=text_body,
        html_body=html_body,
        recipients=recipients,
        from_address=from_address,
    )


def _send_via_resend(
    *,
    api_key: str,
    subject: str,
    text_body: str,
    html_body: str,
    recipients: list[str],
    from_address: str,
) -> None:
    """Send email via Resend's HTTP API. Simple, reliable, one env var."""
    payload = json.dumps({
        "from": from_address,
        "to": recipients,
        "subject": subject,
        "html": html_body,
        "text": text_body,
    }).encode("utf-8")

    req = Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "CRCallClassifier/1.0",
        },
        method="POST",
    )

    try:
        with urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode())
            print(f"  Email sent via Resend (id: {result.get('id', 'unknown')})", file=sys.stderr)
    except HTTPError as e:
        body = e.read().decode() if e.fp else ""
        raise RuntimeError(
            f"Resend API error {e.code}: {body}"
        ) from e


def _send_via_smtp(
    *,
    subject: str,
    text_body: str,
    html_body: str,
    recipients: list[str],
    from_address: Optional[str] = None,
) -> None:
    """Fallback: send email via SMTP."""
    host = os.environ.get("SMTP_HOST", "")
    port = int(os.environ.get("SMTP_PORT", "587"))
    username = os.environ.get("SMTP_USERNAME", "")
    password = os.environ.get("SMTP_PASSWORD", "")
    sender = from_address or os.environ.get("SMTP_FROM", username)

    if not all([host, username, password]):
        raise RuntimeError(
            "Email not configured. Set RESEND_API_KEY (preferred) or "
            "SMTP_HOST + SMTP_USERNAME + SMTP_PASSWORD in environment variables."
        )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(host, port) as server:
        server.starttls()
        server.login(username, password)
        server.sendmail(sender, recipients, msg.as_string())
    print(f"  Email sent via SMTP ({host})", file=sys.stderr)
